/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eegsmart_hellofromjni_Jni */

#ifndef _Included_eegsmart_hellofromjni_Jni
#define _Included_eegsmart_hellofromjni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eegsmart_hellofromjni_Jni
 * Method:    sleepAlgo
 * Signature: (I[C)V
 */
JNIEXPORT void JNICALL Java_eegsmart_hellofromjni_Jni_sleepAlgo
  (JNIEnv *, jclass, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
