/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eegsmart_jnitest_JNIUtils */

#ifndef _Included_eegsmart_jnitest_JNIUtils
#define _Included_eegsmart_jnitest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eegsmart_jnitest_JNIUtils
 * Method:    sleepalgo
 * Signature: (I[C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eegsmart_jnitest_JNIUtils_sleepalgo
  (JNIEnv *, jclass, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
